### ISSUE TITLE
Pages 187 and 188: In the example code, on page 187 operator+ throws runtime_error but in use on page 188 the catch only catches overflow_error.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#83] opened 2019-12-30 16:56 UTC
The exception thrown by operator+ on page 187 would not be caught by the catch on page 188.

Catch blocks only catch **children** of exception types. The exception type overflow_error is a child of runtime_error.

Besides the mistake in the example code, the subsequent text also refers to the wrong thing too:

> This causes an overflow, which is detected by the operator+ overload and results in a thrown **overflow_error**.

**Comment by JLospinoso** [comment] 2020-01-01 15:51
Hi @WraithGlade, thanks for reporting! Please note this is a duplicate of https://github.com/JLospinoso/ccc/issues/9

**Closed by JLospinoso** 2020-01-01 15:51 UTC
Labels: duplicate
