### ISSUE TITLE
p319 Caption to Listing 10-41 should read Boost Test instead of Google Test

### ISSUE THREAD

**Issue by thederz** [JLospinoso/ccc#50] opened 2019-12-12 03:40 UTC
The caption to Listing 10-41 reads: "_Listing 10-41: Using Google Test to implement the `AutoBrake` unit tests_"

Instead, it should read: "_Listing 10-41: Using Boost Test to implement the `AutoBrake` unit tests_"

**Comment by JLospinoso** [comment] 2019-12-13 19:27
Thanks, @thederz! (Closing, duplicate of #34.)

**Closed by JLospinoso** 2019-12-13 19:27 UTC
